# keys need single quotes in case you have double quotes in html
# correct: key = '<p id="myid">'
# not correct: key = "<p id="myid">"
# Ethereal Template by: AJ / HTML5UP
# Demo images by: 
# hugo config.toml and partials by: Jan Stuehler, http://github.com/stueja
baseURL = 'http://example.org/'
languageCode = 'en'
title = 'example site'
defaultContentLanguage = 'en'
themeDir = '../..'
theme = 'hugo-theme-html5up-ethereal'

[params]
author			=	'The Author'
keywords		=	['', '', '']
copyright		=	'Unnamed'

# contact panel parameters
[params.contact]
sectionclassstring = 'panel color4-alt'
textdivclassstring = 'intro color4'
headline = 'Contact'
paragraph = 'Sed vel nibh libero. Mauris et lorem pharetra massa lorem turpis congue pulvinar. Vivamus sed feugiat finibus. Duis amet bibendum amet sed. Duis mauris ex, dapibus sed ligula tempus volutpat magna etiam.'
formdivclassstring = 'inner columns divided'
innerdivclassstring = 'span-3-25'
formmethod = 'post'
formaction = '#'
socialclassstring = 'span-1-5'

# contact form parameters
# single brackets [ ]
[params.contact.messagebox]
classstring = 'field'
id = 'message'
label = 'Message'

[params.contact.submitbutton]
classstring = 'button special'
value = 'Send Message'

# contact form fields
# double brackets [[ ]]
[[params.contact.formfield]]
classstring = 'field half'
id = 'name'
label = 'Name'
inputtype = 'text'

[[params.contact.formfield]]
classstring = 'field half'
id = 'email'
label = 'Email'
inputtype = 'email'


# social icons and urls
# double brackets [[ ]]
[[params.contact.social]]
tag = 'on facebook'
ico = 'fa-facebook'
url = 'https://www.facebook.com/Html5up-349133815294046/'

[[params.contact.social]]
tag = 'on twitter'
ico = 'fa-twitter'
url = 'https://twitter.com/ajlkn/'

[[params.contact.social]]
tag = 'on snapchat'
ico = 'fa-snapchat-ghost'
url = '#'

[[params.contact.social]]
tag = 'on instagram'
ico = 'fa-instagram'
url = '#'

[[params.contact.social]]
tag = 'on medium'
ico = 'fa-medium'
url = '#'



# panels
# 1. params.panel.before
# 2. params.panel.after
[params.panel]

# 1. params.panel.before
# double brackets [[ ]]
[[params.panel.before]]
  order       = 1
  anchorid    = ''
  classstring = 'panel banner right'

  [[params.panel.before.inner]]
    order = 1
	classstring = 'content color0 span-3-75'
	headlinesize = 'h1'
	headlineclass = 'major'
	headline = 'Hello, my name<br />is Ethereal'
	paragraph = 'This is <strong>Ethereal</strong>, a free site template by AJ for <a href="https://html5up.net">HTML5 UP</a>. It’s fully responsive, built on HTML5 and CSS3, and released entirely for free under the Creative Commons license. Hope you dig it :)'
	addhtml = '<ul class="actions"><li><a href="#second" class="button special color1 circle icon fa-angle-right">Next</a></li></ul>'
	imagepath = ''
    imagealt = ''
	dataposition = ''
	htmlfile = ''

  [[params.panel.before.inner]]
    order = 2
	classstring = 'image filtered span-1-75'
	headlinesize = 'h2'
	headlineclass = 'major'
	headline = ''
	paragraph = ''
	addhtml = ''
	imagepath = '/images/pic01.jpg'
    imagealt = ''
	dataposition = '25% 25%'
	htmlfile = ''


[[params.panel.before]]
  order       = 2
  anchorid    = 'second'
  classstring = 'panel spotlight medium right'

  [[params.panel.before.inner]]
    order = 1
	classstring = 'content span-7'
	headlinesize = 'h2'
	headlineclass = 'major'
	headline = 'Sed etiam aenean'
	paragraph = 'Mauris et ligula arcu. Proin dapibus convallis accumsan. Lorem maximus hendrerit orci, sit amet elementum massa hendrerit sed. Donec et ullamcorper ligula. Suspendisse amet potenti. Ut pretium libero eleifend euismod sed tristique. Quisque dictum magna risus, id ultricies justo sagittis vitae. Sed id odio tempor, porttitor elit amet, gravida hendrerit fringilla lorem ipsum dolor.'
	addhtml = ''
	imagepath = ''
    imagealt = ''
	dataposition = ''
	htmlfile = ''

  [[params.panel.before.inner]]
    order = 2
	classstring = 'image filtered tinted'
	headlinesize = 'h2'
	headlineclass = 'major'
	headline = ''
	paragraph = ''
	addhtml = ''
	imagepath = '/images/pic02.jpg'
    imagealt = ''
	dataposition = 'top left'
	htmlfile = ''


[[params.panel.before]]
  order       = 3
  anchorid    = ''
  classstring = 'panel color1'

  [[params.panel.before.inner]]
    order = 1
	classstring = 'intro joined'
	headlinesize = 'h2'
	headlineclass = 'major'
	headline = 'Amet lorem'
	paragraph = 'Sed vel nibh libero. Mauris et lorem pharetra massa lorem turpis congue pulvinar. Vivamus sed feugiat finibus. Duis amet bibendum amet sed. Duis mauris ex, dapibus sed ligula tempus volutpat magna etiam.'
	addhtml = ''
	imagepath = ''
    imagealt = ''
	dataposition = ''
	htmlfile = ''

  [[params.panel.before.inner]]
    order = 2
	classstring = 'inner'
	headlinesize = ''
	headlineclass = ''
	headline = ''
	paragraph = ''
	addhtml = '''
<ul class="grid-icons three connected">
	<li><span class="icon fa-diamond"><span class="label">Lorem</span></span></li>
	<li><span class="icon fa-camera-retro"><span class="label">Ipsum</span></span></li>
	<li><span class="icon fa-cog"><span class="label">Dolor</span></span></li>
	<li><span class="icon fa-paper-plane"><span class="label">Sit</span></span></li>
	<li><span class="icon fa-bar-chart"><span class="label">Amet</span></span></li>
	<li><span class="icon fa-code"><span class="label">Nullam</span></span></li>
</ul>
	'''
	imagepath = ''
    imagealt = ''
	dataposition = ''
	htmlfile = ''


[[params.panel.before]]
  order       = 4
  anchorid    = ''
  classstring = 'panel spotlight large left'

  [[params.panel.before.inner]]
    order = 1
	classstring = 'content span-5'
	headlinesize = 'h2'
	headlineclass = 'major'
	headline = 'Magna amet tempus'
	paragraph = 'Mauris a cursus velit. Nunc lacinia sollicitudin egestas bibendum, magna dui bibendum ex, sagittis commodo enim risus sed magna nulla. Vestibulum ut consequat velit. Curabitur vitae libero lorem. Quisque iaculis porttitor blandit. Nullam quis sagittis maximus. Sed vel nibh libero. Mauris et lorem pharetra massa lorem turpis congue pulvinar.'
	addhtml = ''
	imagepath = ''
    imagealt = ''
	dataposition = ''
	htmlfile = ''

  [[params.panel.before.inner]]
    order = 2
	classstring = 'image filtered tinted'
	headlinesize = ''
	headlineclass = ''
	headline = ''
	paragraph = ''
	addhtml = ''
	imagepath = '/images/pic03.jpg'
    imagealt = ''
	dataposition = 'top right'
	htmlfile = ''


[[params.panel.before]]
  order       = 5
  anchorid    = ''
  classstring = 'panel'

  [[params.panel.before.inner]]
    order = 1
	classstring = 'intro color2'
	headlinesize = 'h2'
	headlineclass = 'major'
	headline = 'Elit integer'
	paragraph = 'Sed vel nibh libero. Mauris et lorem pharetra massa lorem turpis congue pulvinar. Vivamus sed feugiat finibus. Duis amet bibendum amet sed. Duis mauris ex, dapibus sed ligula tempus volutpat magna etiam.'
	addhtml = ''
	imagepath = ''
    imagealt = ''
	dataposition = ''
	htmlfile = ''

  [[params.panel.before.inner]]
    order = 2
	classstring = 'gallery'
	headlinesize = ''
	headlineclass = ''
	headline = ''
	paragraph = ''
	addhtml = '''
	<div class="group span-3">
			<a href="/images/gallery/fulls/01.jpg" class="image filtered span-3" data-position="bottom"><img src="/images/gallery/thumbs/01.jpg" alt="" /></a>
			<a href="/images/gallery/fulls/02.jpg" class="image filtered span-1-5" data-position="center"><img src="/images/gallery/thumbs/02.jpg" alt="" /></a>
			<a href="/images/gallery/fulls/03.jpg" class="image filtered span-1-5" data-position="bottom"><img src="/images/gallery/thumbs/03.jpg" alt="" /></a>
		</div>
		<a href="/images/gallery/fulls/04.jpg" class="image filtered span-2-5" data-position="top"><img src="/images/gallery/thumbs/04.jpg" alt="" /></a>
		<div class="group span-4-5">
			<a href="/images/gallery/fulls/05.jpg" class="image filtered span-3" data-position="top"><img src="/images/gallery/thumbs/05.jpg" alt="" /></a>
			<a href="/images/gallery/fulls/06.jpg" class="image filtered span-1-5" data-position="center"><img src="/images/gallery/thumbs/06.jpg" alt="" /></a>
			<a href="/images/gallery/fulls/07.jpg" class="image filtered span-1-5" data-position="bottom"><img src="/images/gallery/thumbs/07.jpg" alt="" /></a>
			<a href="/images/gallery/fulls/08.jpg" class="image filtered span-3" data-position="top"><img src="/images/gallery/thumbs/08.jpg" alt="" /></a>
		</div>
		<a href="/images/gallery/fulls/09.jpg" class="image filtered span-2-5" data-position="right"><img src="/images/gallery/thumbs/09.jpg" alt="" /></a>
	'''
	imagepath = ''
    imagealt = ''
	dataposition = ''
	htmlfile = ''



# an empty before-block for reference
#[[params.panel.before]]
#  order       = 7
#  anchorid    = ''
#  classstring = ''
#
#  [[params.panel.before.inner]]
#    order = 1
#	classstring = ''
#	headlinesize = ''
#	headlineclass = ''
#	headline = ''
#	paragraph = ''
#	addhtml = ''
#	imagepath = ''
#    imagealt = ''
#	dataposition = ''
#	htmlfile = ''
#
#  [[params.panel.before.inner]]
#    order = 2
#	classstring = ''
#	headlinesize = ''
#	headlineclass = ''
#	headline = ''
#	paragraph = ''
#	addhtml = ''
#	imagepath = ''
#    imagealt = ''
#	dataposition = ''
#	htmlfile = ''

# 2. params.panel.after
# double brackets [[ ]]
# an empty after-block for reference
#[[params.panel.after]]
#  order       = 1
#  anchorid    = ''
#  classstring = ''
#
#  [[params.panel.after.inner]]
#    order = 1
#	classstring = ''
#	headlinesize = ''
#	headlineclass = ''
#	headline = ''
#	paragraph = ''
#	addhtml = ''
#	imagepath = ''
#    imagealt = ''
#	dataposition = ''
#	htmlfile = ''
#
#  [[params.panel.after.inner]]
#    order = 2
#	classstring = ''
#	headlinesize = ''
#	headlineclass = ''
#	headline = ''
#	paragraph = ''
#	addhtml = ''
#	imagepath = ''
#    imagealt = ''
#	dataposition = ''
#	htmlfile = ''


